[package]
name = "andiron"
version = "0.1.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2024"
description = "A readline library for maqi."
repository = "https://github.com/ynqa/maqi"
license = "MIT"
readme = "README.md"
publish = false

[dependencies]
crossterm = "0.29.0"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[dev-dependencies]
portable-pty = "0.9.0"
termharness = "0.4.0"

[[test]]
name = "terminal_scenarios"
harness = false
