//! Deterministic KDL emission with Usage parser validation.
use std::collections::BTreeMap;
use std::fmt::Write;

use anyhow::{Context, Result, ensure};

use crate::model::{Flag, Manual};

fn quote(text: &str) -> String {
    // JSON and KDL share the simple escapes used here, but Unicode control
    // escapes differ (JSON: \\u0000, KDL: \\u{0}).
    let mut result = String::from("\"");
    for ch in text.chars() {
        match ch {
            '"' => result.push_str("\\\""),
            '\\' => result.push_str("\\\\"),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            ch if ch.is_control() => {
                write!(result, "\\u{{{:x}}}", ch as u32).unwrap();
            }
            ch => result.push(ch),
        }
    }
    result.push('"');
    result
}

pub fn generate(bin: &str, manuals: &[Manual]) -> Result<String> {
    ensure!(
        !bin.is_empty() && !bin.chars().any(char::is_whitespace),
        "bin must be a single command name"
    );
    let mut commands = BTreeMap::new();
    for manual in manuals {
        ensure!(
            manual.command.first().is_some_and(|name| name == bin),
            "{}: command {:?} does not belong to {bin}",
            manual.source,
            manual.command
        );
        let key = manual.command[1..].to_vec();
        ensure!(
            commands.insert(key, manual).is_none(),
            "duplicate command path: {:?}",
            manual.command
        );
    }
    let root = commands
        .get(&Vec::new())
        .context("root command manual is missing")?;
    for key in commands.keys() {
        ensure!(
            key.is_empty() || commands.contains_key(&key[..key.len() - 1]),
            "parent manual missing for {}",
            key.join(" ")
        );
    }
    let mut output = format!(
        "// Generated by man2usage; do not edit.\nname {}\nbin {}\nabout {}\n",
        quote(bin),
        quote(bin),
        quote(&root.help)
    );
    emit(&mut output, &commands, &[], 0);
    output
        .parse::<usage::Spec>()
        .context("generated Usage specification is invalid")?;
    Ok(output)
}

fn emit(
    output: &mut String,
    commands: &BTreeMap<Vec<String>, &Manual>,
    key: &[String],
    depth: usize,
) {
    let indent = "    ".repeat(depth);
    let manual = commands[key];
    // Quote source names so an unusual filename cannot inject KDL lines.
    writeln!(output, "{indent}// Source: {}", quote(&manual.source)).unwrap();
    writeln!(output, "{indent}arg \"[args]...\"").unwrap();
    // Inherited options are explicit unless every descendant documents the
    // same option as inherited, in which case it can be emitted once as global.
    for flag in manual.flags.iter().chain(&manual.inherited) {
        if inherited_from_ancestor(commands, key, flag) {
            continue;
        }
        let mut spelling = flag.names.join(" ");
        if let Some(value) = &flag.value {
            write!(spelling, " <{value}>").unwrap();
        }
        write!(
            output,
            "{indent}flag {} help={}",
            quote(&spelling),
            quote(&flag.help)
        )
        .unwrap();
        if is_global(commands, key, flag) {
            output.push_str(" global=#true");
        }
        if flag.repeated {
            output.push_str(" var=#true");
        }
        if flag.choices.is_empty() {
            output.push('\n');
        } else {
            output.push_str(" {\n");
            writeln!(
                output,
                "{indent}    choices {}",
                flag.choices
                    .iter()
                    .map(|c| quote(c))
                    .collect::<Vec<_>>()
                    .join(" ")
            )
            .unwrap();
            writeln!(output, "{indent}}}").unwrap();
        }
    }
    for (child, manual) in commands {
        if child.len() == key.len() + 1 && child.starts_with(key) {
            writeln!(
                output,
                "{indent}cmd {} help={} {{",
                quote(child.last().unwrap()),
                quote(&manual.help)
            )
            .unwrap();
            emit(output, commands, child, depth + 1);
            writeln!(output, "{indent}}}").unwrap();
        }
    }
}

fn is_global(commands: &BTreeMap<Vec<String>, &Manual>, key: &[String], flag: &Flag) -> bool {
    let children = commands
        .iter()
        .filter(|(path, _)| path.len() > key.len() && path.starts_with(key))
        .map(|(_, m)| *m)
        .collect::<Vec<_>>();
    !children.is_empty() && children.iter().all(|child| child.inherited.contains(flag))
}

fn inherited_from_ancestor(
    commands: &BTreeMap<Vec<String>, &Manual>,
    key: &[String],
    flag: &Flag,
) -> bool {
    (0..key.len()).any(|depth| {
        let ancestor = commands[&key[..depth]];
        ancestor
            .flags
            .iter()
            .chain(&ancestor.inherited)
            .any(|parent| parent == flag && is_global(commands, &key[..depth], parent))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manual(command: &[&str], flags: Vec<Flag>, inherited: Vec<Flag>) -> Manual {
        Manual {
            command: command.iter().map(|s| s.to_string()).collect(),
            source: format!("{}.1", command.join("-")),
            help: "Help".into(),
            flags,
            inherited,
        }
    }

    #[test]
    fn inherited_flags_do_not_leak_into_commands_that_do_not_document_them() {
        let flag = Flag {
            names: vec!["--context".into()],
            value: Some("value".into()),
            repeated: false,
            choices: vec![],
            help: "Select context".into(),
        };
        let mut manuals = vec![
            manual(&["tool"], vec![flag.clone()], vec![]),
            manual(&["tool", "get"], vec![], vec![flag.clone()]),
            manual(&["tool", "version"], vec![], vec![]),
        ];
        let spec: usage::Spec = generate("tool", &manuals).unwrap().parse().unwrap();
        assert!(!spec.cmd.flags[0].global);
        assert_eq!(spec.cmd.subcommands["get"].flags.len(), 1);
        assert!(spec.cmd.subcommands["version"].flags.is_empty());
        manuals[2].inherited.push(flag);
        let spec: usage::Spec = generate("tool", &manuals).unwrap().parse().unwrap();
        assert!(spec.cmd.flags[0].global);
        assert!(
            spec.cmd
                .subcommands
                .values()
                .all(|child| child.flags.is_empty())
        );
    }
}
