.TH EXAMPLE 1
.SH NAME
example \- process input files
.SH SYNOPSIS
.B example
[OPTIONS] [FILE...]
.SH OPTIONS
.TP
.BR \-v ", " \-\-verbose
Print additional information.
.TP
.BR \-o ", " \-\-output " FILE"
Write output to FILE.
.TP
.BI \-\-mode= KIND
One of: fast|careful.
.TP
.BR \-\-color [=WHEN]
Enable color with an optional timing value.
